export const LOOKUP_MOVIE_STARTING = 'LOOKUP_MOVIE_STARTING';
export const LOOKUP_MOVIE_SUCCESS = 'LOOKUP_MOVIE_SUCCESS';

export const SEARCH_STARTING = 'SEARCH_STARTING';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';

export const REQUEST_ERROR = 'REQUEST_ERROR';
